//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesst1.Models
{
    using System;
    using System.Collections.Generic;

    using System.Linq;
    public partial class Cart
    {
        public int CartID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
    
}
